# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c3f9c348f4427382010c567b7c6eafc9022e6e2db2319302d11cb57178b1bace660311a3261d39d18edab3bfdb9303278f65933c419d2a4b21c4309c975b3c3

test:
  secret_key_base: 9760f62261430cf4a2c8e5ba56cce97225ba08690ba57130a3d96612ce2680869b17797a643b65fda170541b1ca5fb235fd8909550dbaadb5b4cb0b029e0588f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
